#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : trollius
Version  : 2.1
Release  : 25
URL      : https://pypi.python.org/packages/source/t/trollius/trollius-2.1.tar.gz
Source0  : https://pypi.python.org/packages/source/t/trollius/trollius-2.1.tar.gz
Summary  : Port of the Tulip project (asyncio module, PEP 3156) on Python 2
Group    : Development/Tools
License  : Apache-2.0
Requires: trollius-python
BuildRequires : futures
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python-mock
BuildRequires : python3-dev
BuildRequires : setuptools

%description
Trollius provides infrastructure for writing single-threaded concurrent
code using coroutines, multiplexing I/O access over sockets and other
resources, running network clients and servers, and other related primitives.
Here is a more detailed list of the package contents:

%package python
Summary: python components for the trollius package.
Group: Default

%description python
python components for the trollius package.


%prep
%setup -q -n trollius-2.1

%build
export LANG=C
export SOURCE_DATE_EPOCH=1484581710
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1484581710
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
