#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : trollius
Version  : 2.1
Release  : 28
URL      : http://pypi.debian.net/trollius/trollius-2.1.tar.gz
Source0  : http://pypi.debian.net/trollius/trollius-2.1.tar.gz
Summary  : Port of the Tulip project (asyncio module, PEP 3156) on Python 2
Group    : Development/Tools
License  : Apache-2.0
Requires: trollius-python
Requires: futures
Requires: six
BuildRequires : futures
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python-mock
BuildRequires : python3-dev
BuildRequires : setuptools

%description
code using coroutines, multiplexing I/O access over sockets and other
        resources, running network clients and servers, and other related primitives.

%package python
Summary: python components for the trollius package.
Group: Default

%description python
python components for the trollius package.


%prep
%setup -q -n trollius-2.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1503082355
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1503082355
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python2*/*
/usr/lib/python3*/*
